-- Generated from https://docs.fivem.net/docs/game-references/vehicle-references/vehicle-models/
-- Unsupported models are filtered again in client.lua for the active game build.
BaseVehicles = {
    { model = 'asbo', label = 'Asbo', category = 'Compacts', supported = true },
    { model = 'blista', label = 'Blista', category = 'Compacts', supported = true },
    { model = 'brioso', label = 'Brioso R/A', category = 'Compacts', supported = true },
    { model = 'brioso2', label = 'Brioso 300', category = 'Compacts', supported = true },
    { model = 'brioso3', label = 'Brioso 300 Widebody', category = 'Compacts', supported = true },
    { model = 'club', label = 'Club', category = 'Compacts', supported = true },
    { model = 'dilettante', label = 'Dilettante', category = 'Compacts', supported = true },
    { model = 'dilettante2', label = 'Dilettante', category = 'Compacts', supported = true },
    { model = 'issi2', label = 'Issi', category = 'Compacts', supported = true },
    { model = 'issi3', label = 'Issi Classic', category = 'Compacts', supported = true },
    { model = 'issi4', label = 'Apocalypse Issi', category = 'Compacts', supported = true },
    { model = 'issi5', label = 'Future Shock Issi', category = 'Compacts', supported = true },
    { model = 'issi6', label = 'Nightmare Issi', category = 'Compacts', supported = true },
    { model = 'kanjo', label = 'Blista Kanjo', category = 'Compacts', supported = true },
    { model = 'panto', label = 'Panto', category = 'Compacts', supported = true },
    { model = 'prairie', label = 'Prairie', category = 'Compacts', supported = true },
    { model = 'rhapsody', label = 'Rhapsody', category = 'Compacts', supported = true },
    { model = 'weevil', label = 'Weevil', category = 'Compacts', supported = true },
    { model = 'asea', label = 'Asea', category = 'Sedans', supported = true },
    { model = 'asea2', label = 'Asea', category = 'Sedans', supported = true },
    { model = 'asterope', label = 'Asterope', category = 'Sedans', supported = true },
    { model = 'asterope2', label = 'Asterope GZ', category = 'Sedans', supported = true },
    { model = 'cinquemila', label = 'Cinquemila', category = 'Sedans', supported = true },
    { model = 'cog55', label = 'Cognoscenti 55', category = 'Sedans', supported = true },
    { model = 'cog552', label = 'Cognoscenti 55 (Armored)', category = 'Sedans', supported = true },
    { model = 'cognoscenti', label = 'Cognoscenti', category = 'Sedans', supported = true },
    { model = 'cognoscenti2', label = 'Cognoscenti (Armored)', category = 'Sedans', supported = true },
    { model = 'deity', label = 'Deity', category = 'Sedans', supported = true },
    { model = 'driftchavosv6', label = 'Chavos V6', category = 'Sedans', supported = true },
    { model = 'drifthardy', label = 'Hardy', category = 'Sedans', supported = true },
    { model = 'emperor', label = 'Emperor', category = 'Sedans', supported = true },
    { model = 'emperor2', label = 'Emperor', category = 'Sedans', supported = true },
    { model = 'emperor3', label = 'Emperor', category = 'Sedans', supported = true },
    { model = 'fugitive', label = 'Fugitive', category = 'Sedans', supported = true },
    { model = 'glendale', label = 'Glendale', category = 'Sedans', supported = true },
    { model = 'glendale2', label = 'Glendale Custom', category = 'Sedans', supported = true },
    { model = 'hardy', label = 'Hardy', category = 'Sedans', supported = true },
    { model = 'impaler5', label = 'Impaler SZ', category = 'Sedans', supported = true },
    { model = 'ingot', label = 'Ingot', category = 'Sedans', supported = true },
    { model = 'intruder', label = 'Intruder', category = 'Sedans', supported = true },
    { model = 'limo2', label = 'Turreted Limo', category = 'Sedans', supported = true },
    { model = 'minimus', label = 'Minimus', category = 'Sedans', supported = true },
    { model = 'premier', label = 'Premier', category = 'Sedans', supported = true },
    { model = 'primo', label = 'Primo', category = 'Sedans', supported = true },
    { model = 'primo2', label = 'Primo Custom', category = 'Sedans', supported = true },
    { model = 'regina', label = 'Regina', category = 'Sedans', supported = true },
    { model = 'rhinehart', label = 'Rhinehart', category = 'Sedans', supported = true },
    { model = 'romero', label = 'Romero Hearse', category = 'Sedans', supported = true },
    { model = 'schafter2', label = 'Schafter', category = 'Sedans', supported = true },
    { model = 'schafter5', label = 'Schafter V12 (Armored)', category = 'Sedans', supported = true },
    { model = 'schafter6', label = 'Schafter LWB (Armored)', category = 'Sedans', supported = true },
    { model = 'stafford', label = 'Stafford', category = 'Sedans', supported = true },
    { model = 'stanier', label = 'Stanier', category = 'Sedans', supported = true },
    { model = 'stratum', label = 'Stratum', category = 'Sedans', supported = true },
    { model = 'stretch', label = 'Stretch', category = 'Sedans', supported = true },
    { model = 'superd', label = 'Super Diamond', category = 'Sedans', supported = true },
    { model = 'surge', label = 'Surge', category = 'Sedans', supported = true },
    { model = 'tailgater', label = 'Tailgater', category = 'Sedans', supported = true },
    { model = 'tailgater2', label = 'Tailgater S', category = 'Sedans', supported = true },
    { model = 'warrener', label = 'Warrener', category = 'Sedans', supported = true },
    { model = 'warrener2', label = 'Warrener HKR', category = 'Sedans', supported = true },
    { model = 'washington', label = 'Washington', category = 'Sedans', supported = true },
    { model = 'aleutian', label = 'Aleutian', category = 'SUVs', supported = true },
    { model = 'astron', label = 'Astron', category = 'SUVs', supported = true },
    { model = 'baller', label = 'Baller', category = 'SUVs', supported = true },
    { model = 'baller2', label = 'Baller', category = 'SUVs', supported = true },
    { model = 'baller3', label = 'Baller LE', category = 'SUVs', supported = true },
    { model = 'baller4', label = 'Baller LE LWB', category = 'SUVs', supported = true },
    { model = 'baller5', label = 'Baller LE (Armored)', category = 'SUVs', supported = true },
    { model = 'baller6', label = 'Baller LE LWB (Armored)', category = 'SUVs', supported = true },
    { model = 'baller7', label = 'Baller ST', category = 'SUVs', supported = true },
    { model = 'baller8', label = 'Baller ST-D', category = 'SUVs', supported = true },
    { model = 'bjxl', label = 'BeeJay XL', category = 'SUVs', supported = true },
    { model = 'cavalcade', label = 'Cavalcade', category = 'SUVs', supported = true },
    { model = 'cavalcade2', label = 'Cavalcade', category = 'SUVs', supported = true },
    { model = 'cavalcade3', label = 'Cavalcade XL', category = 'SUVs', supported = true },
    { model = 'contender', label = 'Contender', category = 'SUVs', supported = true },
    { model = 'dorado', label = 'Dorado', category = 'SUVs', supported = true },
    { model = 'dubsta', label = 'Dubsta', category = 'SUVs', supported = true },
    { model = 'dubsta2', label = 'Dubsta', category = 'SUVs', supported = true },
    { model = 'everon3', label = 'Everon RS', category = 'SUVs', supported = true },
    { model = 'fq2', label = 'FQ 2', category = 'SUVs', supported = true },
    { model = 'granger', label = 'Granger', category = 'SUVs', supported = true },
    { model = 'granger2', label = 'Granger 3600LX', category = 'SUVs', supported = true },
    { model = 'gresley', label = 'Gresley', category = 'SUVs', supported = true },
    { model = 'habanero', label = 'Habanero', category = 'SUVs', supported = true },
    { model = 'huntley', label = 'Huntley S', category = 'SUVs', supported = true },
    { model = 'issi8', label = 'Issi Rally', category = 'SUVs', supported = true },
    { model = 'iwagen', label = 'I-Wagen', category = 'SUVs', supported = true },
    { model = 'jubilee', label = 'Jubilee', category = 'SUVs', supported = true },
    { model = 'landstalker', label = 'Landstalker', category = 'SUVs', supported = true },
    { model = 'landstalker2', label = 'Landstalker XL', category = 'SUVs', supported = true },
    { model = 'mesa', label = 'Mesa', category = 'SUVs', supported = true },
    { model = 'mesa2', label = 'Mesa', category = 'SUVs', supported = true },
    { model = 'novak', label = 'Novak', category = 'SUVs', supported = true },
    { model = 'patriot', label = 'Patriot', category = 'SUVs', supported = true },
    { model = 'patriot2', label = 'Patriot Stretch', category = 'SUVs', supported = true },
    { model = 'radi', label = 'Radius', category = 'SUVs', supported = true },
    { model = 'rebla', label = 'Rebla GTS', category = 'SUVs', supported = true },
    { model = 'rocoto', label = 'Rocoto', category = 'SUVs', supported = true },
    { model = 'seminole', label = 'Seminole', category = 'SUVs', supported = true },
    { model = 'seminole2', label = 'Seminole Frontier', category = 'SUVs', supported = true },
    { model = 'serrano', label = 'Serrano', category = 'SUVs', supported = true },
    { model = 'squaddie', label = 'Squaddie', category = 'SUVs', supported = true },
    { model = 'toros', label = 'Toros', category = 'SUVs', supported = true },
    { model = 'vivanite', label = 'Vivanite', category = 'SUVs', supported = true },
    { model = 'woodlander', label = 'Woodlander', category = 'SUVs', supported = true },
    { model = 'xls', label = 'XLS', category = 'SUVs', supported = true },
    { model = 'xls2', label = 'XLS (Armored)', category = 'SUVs', supported = true },
    { model = 'cogcabrio', label = 'Cognoscenti Cabrio', category = 'Coupes', supported = true },
    { model = 'driftfr36', label = 'FR36', category = 'Coupes', supported = true },
    { model = 'driftsent2', label = 'Sentinel XS', category = 'Coupes', supported = true },
    { model = 'exemplar', label = 'Exemplar', category = 'Coupes', supported = true },
    { model = 'f620', label = 'F620', category = 'Coupes', supported = true },
    { model = 'felon', label = 'Felon', category = 'Coupes', supported = true },
    { model = 'felon2', label = 'Felon GT', category = 'Coupes', supported = true },
    { model = 'fr36', label = 'FR36', category = 'Coupes', supported = true },
    { model = 'jackal', label = 'Jackal', category = 'Coupes', supported = true },
    { model = 'kanjosj', label = 'Kanjo SJ', category = 'Coupes', supported = true },
    { model = 'oracle', label = 'Oracle XS', category = 'Coupes', supported = true },
    { model = 'oracle2', label = 'Oracle', category = 'Coupes', supported = true },
    { model = 'postlude', label = 'Postlude', category = 'Coupes', supported = true },
    { model = 'previon', label = 'Previon', category = 'Coupes', supported = true },
    { model = 'sentinel', label = 'Sentinel XS', category = 'Coupes', supported = true },
    { model = 'sentinel2', label = 'Sentinel', category = 'Coupes', supported = true },
    { model = 'sentinel6', label = 'Sentinel XS4', category = 'Coupes', supported = true },
    { model = 'windsor', label = 'Windsor', category = 'Coupes', supported = true },
    { model = 'windsor2', label = 'Windsor Drop', category = 'Coupes', supported = true },
    { model = 'zion', label = 'Zion', category = 'Coupes', supported = true },
    { model = 'zion2', label = 'Zion Cabrio', category = 'Coupes', supported = true },
    { model = 'blade', label = 'Blade', category = 'Muscle', supported = true },
    { model = 'brigham', label = 'Brigham', category = 'Muscle', supported = true },
    { model = 'broadway', label = 'Broadway', category = 'Muscle', supported = true },
    { model = 'buccaneer', label = 'Buccaneer', category = 'Muscle', supported = true },
    { model = 'buccaneer2', label = 'Buccaneer Custom', category = 'Muscle', supported = true },
    { model = 'buffalo4', label = 'Buffalo STX', category = 'Muscle', supported = true },
    { model = 'buffalo5', label = 'Buffalo EVX', category = 'Muscle', supported = true },
    { model = 'chino', label = 'Chino', category = 'Muscle', supported = true },
    { model = 'chino2', label = 'Chino Custom', category = 'Muscle', supported = true },
    { model = 'clique', label = 'Clique', category = 'Muscle', supported = true },
    { model = 'clique2', label = 'Clique Wagon', category = 'Muscle', supported = true },
    { model = 'coquette3', label = 'Coquette BlackFin', category = 'Muscle', supported = true },
    { model = 'deviant', label = 'Deviant', category = 'Muscle', supported = true },
    { model = 'dominator', label = 'Dominator', category = 'Muscle', supported = true },
    { model = 'dominator2', label = 'Pisswasser Dominator', category = 'Muscle', supported = true },
    { model = 'dominator3', label = 'Dominator GTX', category = 'Muscle', supported = true },
    { model = 'dominator4', label = 'Apocalypse Dominator', category = 'Muscle', supported = true },
    { model = 'dominator5', label = 'Future Shock Dominator', category = 'Muscle', supported = true },
    { model = 'dominator6', label = 'Nightmare Dominator', category = 'Muscle', supported = true },
    { model = 'dominator7', label = 'Dominator ASP', category = 'Muscle', supported = true },
    { model = 'dominator8', label = 'Dominator GTT', category = 'Muscle', supported = true },
    { model = 'dominator9', label = 'Dominator GT', category = 'Muscle', supported = true },
    { model = 'driftdominator9', label = 'Dominator GT', category = 'Muscle', supported = true },
    { model = 'driftdominator10', label = 'Dominator FX', category = 'Muscle', supported = true },
    { model = 'driftgauntlet4', label = 'Gauntlet Hellfire', category = 'Muscle', supported = true },
    { model = 'driftyosemite', label = 'Drift Yosemite', category = 'Muscle', supported = true },
    { model = 'dukes', label = 'Dukes', category = 'Muscle', supported = true },
    { model = 'dukes2', label = "Duke O'Death", category = 'Muscle', supported = true },
    { model = 'dukes3', label = 'Beater Dukes', category = 'Muscle', supported = true },
    { model = 'ellie', label = 'Ellie', category = 'Muscle', supported = true },
    { model = 'eudora', label = 'Eudora', category = 'Muscle', supported = true },
    { model = 'faction', label = 'Faction', category = 'Muscle', supported = true },
    { model = 'faction2', label = 'Faction Custom 1', category = 'Muscle', supported = true },
    { model = 'faction3', label = 'Faction Custom Donk', category = 'Muscle', supported = true },
    { model = 'gauntlet', label = 'Gauntlet', category = 'Muscle', supported = true },
    { model = 'gauntlet2', label = 'Redwood Gauntlet', category = 'Muscle', supported = true },
    { model = 'gauntlet3', label = 'Gauntlet Classic', category = 'Muscle', supported = true },
    { model = 'gauntlet4', label = 'Gauntlet Hellfire', category = 'Muscle', supported = true },
    { model = 'gauntlet5', label = 'Gauntlet Classic Custom', category = 'Muscle', supported = true },
    { model = 'greenwood', label = 'Greenwood', category = 'Muscle', supported = true },
    { model = 'hermes', label = 'Hermes', category = 'Muscle', supported = true },
    { model = 'hotknife', label = 'Hotknife', category = 'Muscle', supported = true },
    { model = 'hustler', label = 'Hustler', category = 'Muscle', supported = true },
    { model = 'impaler', label = 'Impaler', category = 'Muscle', supported = true },
    { model = 'impaler2', label = 'Apocalypse Impaler', category = 'Muscle', supported = true },
    { model = 'impaler3', label = 'Future Shock Impaler', category = 'Muscle', supported = true },
    { model = 'impaler4', label = 'Nightmare Impaler', category = 'Muscle', supported = true },
    { model = 'impaler6', label = 'Impaler LX', category = 'Muscle', supported = true },
    { model = 'imperator', label = 'Apocalypse Imperator', category = 'Muscle', supported = true },
    { model = 'imperator2', label = 'Future Shock Imperator', category = 'Muscle', supported = true },
    { model = 'imperator3', label = 'Nightmare Imperator', category = 'Muscle', supported = true },
    { model = 'lurcher', label = 'Lurcher', category = 'Muscle', supported = true },
    { model = 'manana2', label = 'Manana Custom', category = 'Muscle', supported = true },
    { model = 'moonbeam', label = 'Moonbeam', category = 'Muscle', supported = true },
    { model = 'moonbeam2', label = 'Moonbeam Custom', category = 'Muscle', supported = true },
    { model = 'nightshade', label = 'Nightshade', category = 'Muscle', supported = true },
    { model = 'peyote2', label = 'Peyote Gasser', category = 'Muscle', supported = true },
    { model = 'phoenix', label = 'Phoenix', category = 'Muscle', supported = true },
    { model = 'picador', label = 'Picador', category = 'Muscle', supported = true },
    { model = 'ratloader', label = 'Rat-Loader', category = 'Muscle', supported = true },
    { model = 'ratloader2', label = 'Rat-Truck', category = 'Muscle', supported = true },
    { model = 'ruiner', label = 'Ruiner', category = 'Muscle', supported = true },
    { model = 'ruiner2', label = 'Ruiner 2000', category = 'Muscle', supported = true },
    { model = 'ruiner3', label = 'Ruiner', category = 'Muscle', supported = true },
    { model = 'ruiner4', label = 'Ruiner ZZ-8', category = 'Muscle', supported = true },
    { model = 'sabregt', label = 'Sabre Turbo', category = 'Muscle', supported = true },
    { model = 'sabregt2', label = 'Sabre Turbo Custom', category = 'Muscle', supported = true },
    { model = 'slamvan', label = 'Slamvan', category = 'Muscle', supported = true },
    { model = 'slamvan2', label = 'Lost Slamvan', category = 'Muscle', supported = true },
    { model = 'slamvan3', label = 'Slamvan Custom', category = 'Muscle', supported = true },
    { model = 'slamvan4', label = 'Apocalypse Slamvan', category = 'Muscle', supported = true },
    { model = 'slamvan5', label = 'Future Shock Slamvan', category = 'Muscle', supported = true },
    { model = 'slamvan6', label = 'Nightmare Slamvan', category = 'Muscle', supported = true },
    { model = 'stalion', label = 'Stallion', category = 'Muscle', supported = true },
    { model = 'stalion2', label = 'Burger Shot Stallion', category = 'Muscle', supported = true },
    { model = 'tahoma', label = 'Tahoma Coupe', category = 'Muscle', supported = true },
    { model = 'tampa', label = 'Tampa', category = 'Muscle', supported = true },
    { model = 'tampa3', label = 'Weaponized Tampa', category = 'Muscle', supported = true },
    { model = 'tampa4', label = 'Tampa GT', category = 'Muscle', supported = true },
    { model = 'tulip', label = 'Tulip', category = 'Muscle', supported = true },
    { model = 'tulip2', label = 'Tulip M-100', category = 'Muscle', supported = true },
    { model = 'vamos', label = 'Vamos', category = 'Muscle', supported = true },
    { model = 'vigero', label = 'Vigero', category = 'Muscle', supported = true },
    { model = 'vigero2', label = 'Vigero ZX', category = 'Muscle', supported = true },
    { model = 'vigero3', label = 'Vigero ZX Convertible', category = 'Muscle', supported = true },
    { model = 'virgo', label = 'Virgo', category = 'Muscle', supported = true },
    { model = 'virgo2', label = 'Virgo Classic Custom', category = 'Muscle', supported = true },
    { model = 'virgo3', label = 'Virgo Classic', category = 'Muscle', supported = true },
    { model = 'voodoo', label = 'Voodoo Custom', category = 'Muscle', supported = true },
    { model = 'voodoo2', label = 'Voodoo', category = 'Muscle', supported = true },
    { model = 'weevil2', label = 'Weevil Custom', category = 'Muscle', supported = true },
    { model = 'yosemite', label = 'Yosemite', category = 'Muscle', supported = true },
    { model = 'yosemite2', label = 'Drift Yosemite', category = 'Muscle', supported = true },
    { model = 'ardent', label = 'Ardent', category = 'Sports Classics', supported = true },
    { model = 'astrale', label = 'Astrale', category = 'Sports Classics', supported = true },
    { model = 'btype', label = 'Roosevelt', category = 'Sports Classics', supported = true },
    { model = 'btype2', label = 'Fränken Stange', category = 'Sports Classics', supported = true },
    { model = 'btype3', label = 'Roosevelt Valor', category = 'Sports Classics', supported = true },
    { model = 'casco', label = 'Casco', category = 'Sports Classics', supported = true },
    { model = 'cheburek', label = 'Cheburek', category = 'Sports Classics', supported = true },
    { model = 'cheetah2', label = 'Cheetah Classic', category = 'Sports Classics', supported = true },
    { model = 'cheetah3', label = 'LSCM Cheetah Classic', category = 'Sports Classics', supported = true },
    { model = 'coquette2', label = 'Coquette Classic', category = 'Sports Classics', supported = true },
    { model = 'deluxo', label = 'Deluxo', category = 'Sports Classics', supported = true },
    { model = 'dynasty', label = 'Dynasty', category = 'Sports Classics', supported = true },
    { model = 'fagaloa', label = 'Fagaloa', category = 'Sports Classics', supported = true },
    { model = 'feltzer3', label = 'Feltzer Classic', category = 'Sports Classics', supported = true },
    { model = 'gt500', label = 'GT500', category = 'Sports Classics', supported = true },
    { model = 'gt750', label = 'GT750', category = 'Sports Classics', supported = true },
    { model = 'infernus2', label = 'Infernus Classic', category = 'Sports Classics', supported = true },
    { model = 'itali2', label = 'Itali Classic', category = 'Sports Classics', supported = true },
    { model = 'jb700', label = 'JB 700', category = 'Sports Classics', supported = true },
    { model = 'jb7002', label = 'JB 700W', category = 'Sports Classics', supported = true },
    { model = 'mamba', label = 'Mamba', category = 'Sports Classics', supported = true },
    { model = 'manana', label = 'Manana', category = 'Sports Classics', supported = true },
    { model = 'michelli', label = 'Michelli GT', category = 'Sports Classics', supported = true },
    { model = 'monroe', label = 'Monroe', category = 'Sports Classics', supported = true },
    { model = 'nebula', label = 'Nebula Turbo', category = 'Sports Classics', supported = true },
    { model = 'peyote', label = 'Peyote', category = 'Sports Classics', supported = true },
    { model = 'peyote3', label = 'Peyote Custom', category = 'Sports Classics', supported = true },
    { model = 'pigalle', label = 'Pigalle', category = 'Sports Classics', supported = true },
    { model = 'rapidgt3', label = 'Rapid GT Classic', category = 'Sports Classics', supported = true },
    { model = 'retinue', label = 'Retinue', category = 'Sports Classics', supported = true },
    { model = 'retinue2', label = 'Retinue Mk II', category = 'Sports Classics', supported = true },
    { model = 'savestra', label = 'Savestra', category = 'Sports Classics', supported = true },
    { model = 'stinger', label = 'Stinger', category = 'Sports Classics', supported = true },
    { model = 'stingergt', label = 'Stinger GT', category = 'Sports Classics', supported = true },
    { model = 'stromberg', label = 'Stromberg', category = 'Sports Classics', supported = true },
    { model = 'swinger', label = 'Swinger', category = 'Sports Classics', supported = true },
    { model = 'toreador', label = 'Toreador', category = 'Sports Classics', supported = true },
    { model = 'torero', label = 'Torero', category = 'Sports Classics', supported = true },
    { model = 'tornado', label = 'Tornado', category = 'Sports Classics', supported = true },
    { model = 'tornado2', label = 'Tornado', category = 'Sports Classics', supported = true },
    { model = 'tornado3', label = 'Tornado', category = 'Sports Classics', supported = true },
    { model = 'tornado4', label = 'Tornado', category = 'Sports Classics', supported = true },
    { model = 'tornado5', label = 'Tornado Custom', category = 'Sports Classics', supported = true },
    { model = 'tornado6', label = 'Tornado Rat Rod', category = 'Sports Classics', supported = true },
    { model = 'turismo2', label = 'Turismo Classic', category = 'Sports Classics', supported = true },
    { model = 'viseris', label = 'Viseris', category = 'Sports Classics', supported = true },
    { model = 'z190', label = '190z', category = 'Sports Classics', supported = true },
    { model = 'zion3', label = 'Zion Classic', category = 'Sports Classics', supported = true },
    { model = 'ztype', label = 'Z-Type', category = 'Sports Classics', supported = true },
    { model = 'alpha', label = 'Alpha', category = 'Sports', supported = true },
    { model = 'banshee', label = 'Banshee', category = 'Sports', supported = true },
    { model = 'bestiagts', label = 'Bestia GTS', category = 'Sports', supported = true },
    { model = 'blista2', label = 'Blista Compact', category = 'Sports', supported = true },
    { model = 'blista3', label = 'Go Go Monkey Blista', category = 'Sports', supported = true },
    { model = 'buffalo', label = 'Buffalo', category = 'Sports', supported = true },
    { model = 'buffalo2', label = 'Buffalo S', category = 'Sports', supported = true },
    { model = 'buffalo3', label = 'Sprunk Buffalo', category = 'Sports', supported = true },
    { model = 'calico', label = 'Calico GTF', category = 'Sports', supported = true },
    { model = 'carbonizzare', label = 'Carbonizzare', category = 'Sports', supported = true },
    { model = 'comet2', label = 'Comet', category = 'Sports', supported = true },
    { model = 'comet3', label = 'Comet Retro Custom', category = 'Sports', supported = true },
    { model = 'comet4', label = 'Comet Safari', category = 'Sports', supported = true },
    { model = 'comet5', label = 'Comet SR', category = 'Sports', supported = true },
    { model = 'comet6', label = 'Comet S2', category = 'Sports', supported = true },
    { model = 'comet7', label = 'Comet S2 Cabrio', category = 'Sports', supported = true },
    { model = 'coquette', label = 'Coquette', category = 'Sports', supported = true },
    { model = 'coquette4', label = 'Coquette D10', category = 'Sports', supported = true },
    { model = 'corsita', label = 'Corsita', category = 'Sports', supported = true },
    { model = 'coureur', label = 'La Coureuse', category = 'Sports', supported = true },
    { model = 'cypher', label = 'Cypher', category = 'Sports', supported = true },
    { model = 'drafter', label = '8F Drafter', category = 'Sports', supported = true },
    { model = 'drifteuros', label = 'Euros', category = 'Sports', supported = true },
    { model = 'driftfuto', label = 'Futo GTX', category = 'Sports', supported = true },
    { model = 'driftjester', label = 'Jester RR', category = 'Sports', supported = true },
    { model = 'driftremus', label = 'Remus', category = 'Sports', supported = true },
    { model = 'driftrt3', label = 'RT3000', category = 'Sports', supported = true },
    { model = 'drifttampa', label = 'Drift Tampa', category = 'Sports', supported = true },
    { model = 'driftzr350', label = 'ZR350', category = 'Sports', supported = true },
    { model = 'elegy', label = 'Elegy Retro Custom', category = 'Sports', supported = true },
    { model = 'elegy2', label = 'Elegy RH8', category = 'Sports', supported = true },
    { model = 'euros', label = 'Euros', category = 'Sports', supported = true },
    { model = 'everon2', label = 'Hotring Everon', category = 'Sports', supported = true },
    { model = 'feltzer2', label = 'Feltzer', category = 'Sports', supported = true },
    { model = 'flashgt', label = 'Flash GT', category = 'Sports', supported = true },
    { model = 'furoregt', label = 'Furore GT', category = 'Sports', supported = true },
    { model = 'fusilade', label = 'Fusilade', category = 'Sports', supported = true },
    { model = 'futo', label = 'Futo', category = 'Sports', supported = true },
    { model = 'futo2', label = 'Futo GTX', category = 'Sports', supported = true },
    { model = 'gauntlet6', label = 'Hotring Hellfire', category = 'Sports', supported = true },
    { model = 'gb200', label = 'GB200', category = 'Sports', supported = true },
    { model = 'growler', label = 'Growler', category = 'Sports', supported = true },
    { model = 'hotring', label = 'Hotring Sabre', category = 'Sports', supported = true },
    { model = 'imorgon', label = 'Imorgon', category = 'Sports', supported = true },
    { model = 'issi7', label = 'Issi Sport', category = 'Sports', supported = true },
    { model = 'italigto', label = 'Itali GTO', category = 'Sports', supported = true },
    { model = 'italirsx', label = 'Itali RSX', category = 'Sports', supported = true },
    { model = 'jester', label = 'Jester', category = 'Sports', supported = true },
    { model = 'jester2', label = 'Jester (Racecar)', category = 'Sports', supported = true },
    { model = 'jester3', label = 'Jester Classic', category = 'Sports', supported = true },
    { model = 'jester4', label = 'Jester RR', category = 'Sports', supported = true },
    { model = 'jugular', label = 'Jugular', category = 'Sports', supported = true },
    { model = 'khamelion', label = 'Khamelion', category = 'Sports', supported = true },
    { model = 'komoda', label = 'Komoda', category = 'Sports', supported = true },
    { model = 'kuruma', label = 'Kuruma', category = 'Sports', supported = true },
    { model = 'kuruma2', label = 'Kuruma (Armored)', category = 'Sports', supported = true },
    { model = 'locust', label = 'Locust', category = 'Sports', supported = true },
    { model = 'lynx', label = 'Lynx', category = 'Sports', supported = true },
    { model = 'massacro', label = 'Massacro', category = 'Sports', supported = true },
    { model = 'massacro2', label = 'Massacro (Racecar)', category = 'Sports', supported = true },
    { model = 'neo', label = 'Neo', category = 'Sports', supported = true },
    { model = 'neon', label = 'Neon', category = 'Sports', supported = true },
    { model = 'ninef', label = '9F', category = 'Sports', supported = true },
    { model = 'ninef2', label = '9F Cabrio', category = 'Sports', supported = true },
    { model = 'omnis', label = 'Omnis', category = 'Sports', supported = true },
    { model = 'omnisegt', label = 'Omnis e-GT', category = 'Sports', supported = true },
    { model = 'panthere', label = 'Panthere', category = 'Sports', supported = true },
    { model = 'paragon', label = 'Paragon R', category = 'Sports', supported = true },
    { model = 'paragon2', label = 'Paragon R (Armored)', category = 'Sports', supported = true },
    { model = 'pariah', label = 'Pariah', category = 'Sports', supported = true },
    { model = 'penumbra', label = 'Penumbra', category = 'Sports', supported = true },
    { model = 'penumbra2', label = 'Penumbra FF', category = 'Sports', supported = true },
    { model = 'r300', label = '300R', category = 'Sports', supported = true },
    { model = 'raiden', label = 'Raiden', category = 'Sports', supported = true },
    { model = 'rapidgt', label = 'Rapid GT', category = 'Sports', supported = true },
    { model = 'rapidgt2', label = 'Rapid GT', category = 'Sports', supported = true },
    { model = 'rapidgt4', label = 'Rapid GT X', category = 'Sports', supported = true },
    { model = 'raptor', label = 'Raptor', category = 'Sports', supported = true },
    { model = 'remus', label = 'Remus', category = 'Sports', supported = true },
    { model = 'revolter', label = 'Revolter', category = 'Sports', supported = true },
    { model = 'rt3000', label = 'RT3000', category = 'Sports', supported = true },
    { model = 'ruston', label = 'Ruston', category = 'Sports', supported = true },
    { model = 'schafter3', label = 'Schafter V12', category = 'Sports', supported = true },
    { model = 'schafter4', label = 'Schafter LWB', category = 'Sports', supported = true },
    { model = 'schlagen', label = 'Schlagen GT', category = 'Sports', supported = true },
    { model = 'schwarzer', label = 'Schwartzer', category = 'Sports', supported = true },
    { model = 'sentinel3', label = 'Sentinel', category = 'Sports', supported = true },
    { model = 'sentinel4', label = 'Sentinel Classic Widebody', category = 'Sports', supported = true },
    { model = 'sentinel5', label = 'Sentinel GTS', category = 'Sports', supported = true },
    { model = 'seven70', label = 'Seven-70', category = 'Sports', supported = true },
    { model = 'sm722', label = 'SM722', category = 'Sports', supported = true },
    { model = 'specter', label = 'Specter', category = 'Sports', supported = true },
    { model = 'specter2', label = 'Specter Custom', category = 'Sports', supported = true },
    { model = 'stingertt', label = 'Itali GTO Stinger TT', category = 'Sports', supported = true },
    { model = 'streiter', label = 'Streiter', category = 'Sports', supported = true },
    { model = 'sugoi', label = 'Sugoi', category = 'Sports', supported = true },
    { model = 'sultan', label = 'Sultan', category = 'Sports', supported = true },
    { model = 'sultan2', label = 'Sultan Classic', category = 'Sports', supported = true },
    { model = 'sultan3', label = 'Sultan RS Classic', category = 'Sports', supported = true },
    { model = 'surano', label = 'Surano', category = 'Sports', supported = true },
    { model = 'tampa2', label = 'Drift Tampa', category = 'Sports', supported = true },
    { model = 'tenf', label = '10F', category = 'Sports', supported = true },
    { model = 'tenf2', label = '10F Widebody', category = 'Sports', supported = true },
    { model = 'tropos', label = 'Tropos Rallye', category = 'Sports', supported = true },
    { model = 'vectre', label = 'Vectre', category = 'Sports', supported = true },
    { model = 'verlierer2', label = 'Verlierer', category = 'Sports', supported = true },
    { model = 'veto', label = 'Veto Classic', category = 'Sports', supported = true },
    { model = 'veto2', label = 'Veto Modern', category = 'Sports', supported = true },
    { model = 'vstr', label = 'V-STR', category = 'Sports', supported = true },
    { model = 'zr350', label = 'ZR350', category = 'Sports', supported = true },
    { model = 'zr380', label = 'Apocalypse ZR380', category = 'Sports', supported = true },
    { model = 'zr3802', label = 'Future Shock ZR380', category = 'Sports', supported = true },
    { model = 'zr3803', label = 'Nightmare ZR380', category = 'Sports', supported = true },
    { model = 'adder', label = 'Adder', category = 'Super', supported = true },
    { model = 'autarch', label = 'Autarch', category = 'Super', supported = true },
    { model = 'banshee2', label = 'Banshee 900R', category = 'Super', supported = true },
    { model = 'bullet', label = 'Bullet', category = 'Super', supported = true },
    { model = 'champion', label = 'Champion', category = 'Super', supported = true },
    { model = 'cheetah', label = 'Cheetah', category = 'Super', supported = true },
    { model = 'cyclone', label = 'Cyclone', category = 'Super', supported = true },
    { model = 'deveste', label = 'Deveste Eight', category = 'Super', supported = true },
    { model = 'emerus', label = 'Emerus', category = 'Super', supported = true },
    { model = 'entity2', label = 'Entity XXR', category = 'Super', supported = true },
    { model = 'entity3', label = 'Entity MT', category = 'Super', supported = true },
    { model = 'entityxf', label = 'Entity XF', category = 'Super', supported = true },
    { model = 'fmj', label = 'FMJ', category = 'Super', supported = true },
    { model = 'fmj2', label = 'FMJ MK V', category = 'Super', supported = true },
    { model = 'furia', label = 'Furia', category = 'Super', supported = true },
    { model = 'gp1', label = 'GP1', category = 'Super', supported = true },
    { model = 'ignus', label = 'Ignus', category = 'Super', supported = true },
    { model = 'infernus', label = 'Infernus', category = 'Super', supported = true },
    { model = 'italigtb', label = 'Itali GTB', category = 'Super', supported = true },
    { model = 'italigtb2', label = 'Itali GTB Custom', category = 'Super', supported = true },
    { model = 'krieger', label = 'Krieger', category = 'Super', supported = true },
    { model = 'le7b', label = 'RE-7B', category = 'Super', supported = true },
    { model = 'lm87', label = 'LM87', category = 'Super', supported = true },
    { model = 'luiva', label = 'Luiva', category = 'Super', supported = true },
    { model = 'nero', label = 'Nero', category = 'Super', supported = true },
    { model = 'nero2', label = 'Nero Custom', category = 'Super', supported = true },
    { model = 'osiris', label = 'Osiris', category = 'Super', supported = true },
    { model = 'penetrator', label = 'Penetrator', category = 'Super', supported = true },
    { model = 'pfister811', label = '811', category = 'Super', supported = true },
    { model = 'prototipo', label = 'X80 Proto', category = 'Super', supported = true },
    { model = 'reaper', label = 'Reaper', category = 'Super', supported = true },
    { model = 's80', label = 'S80RR', category = 'Super', supported = true },
    { model = 'sc1', label = 'SC1', category = 'Super', supported = true },
    { model = 'scramjet', label = 'Scramjet', category = 'Super', supported = true },
    { model = 'sheava', label = 'ETR1', category = 'Super', supported = true },
    { model = 'sultanrs', label = 'Sultan RS', category = 'Super', supported = true },
    { model = 'suzume', label = 'Suzume', category = 'Super', supported = true },
    { model = 't20', label = 'T20', category = 'Super', supported = true },
    { model = 'taipan', label = 'Taipan', category = 'Super', supported = true },
    { model = 'tempesta', label = 'Tempesta', category = 'Super', supported = true },
    { model = 'tezeract', label = 'Tezeract', category = 'Super', supported = true },
    { model = 'thrax', label = 'Thrax', category = 'Super', supported = true },
    { model = 'tigon', label = 'Tigon', category = 'Super', supported = true },
    { model = 'torero2', label = 'Torero XO', category = 'Super', supported = true },
    { model = 'turismo3', label = 'Turismo Omaggio', category = 'Super', supported = true },
    { model = 'turismor', label = 'Turismo R', category = 'Super', supported = true },
    { model = 'tyrant', label = 'Tyrant', category = 'Super', supported = true },
    { model = 'tyrus', label = 'Tyrus', category = 'Super', supported = true },
    { model = 'vacca', label = 'Vacca', category = 'Super', supported = true },
    { model = 'vagner', label = 'Vagner', category = 'Super', supported = true },
    { model = 'vigilante', label = 'Vigilante', category = 'Super', supported = true },
    { model = 'virtue', label = 'Virtue', category = 'Super', supported = true },
    { model = 'visione', label = 'Visione', category = 'Super', supported = true },
    { model = 'voltic', label = 'Voltic', category = 'Super', supported = true },
    { model = 'voltic2', label = 'Rocket Voltic', category = 'Super', supported = true },
    { model = 'xa21', label = 'XA-21', category = 'Super', supported = true },
    { model = 'xtreme', label = 'X-treme', category = 'Super', supported = true },
    { model = 'zeno', label = 'Zeno', category = 'Super', supported = true },
    { model = 'zentorno', label = 'Zentorno', category = 'Super', supported = true },
    { model = 'zorrusso', label = 'Zorrusso', category = 'Super', supported = true },
    { model = 'akuma', label = 'Akuma', category = 'Motorcycles', supported = true },
    { model = 'avarus', label = 'Avarus', category = 'Motorcycles', supported = true },
    { model = 'bagger', label = 'Bagger', category = 'Motorcycles', supported = true },
    { model = 'bati', label = 'Bati 801', category = 'Motorcycles', supported = true },
    { model = 'bati2', label = 'Bati 801RR', category = 'Motorcycles', supported = true },
    { model = 'bf400', label = 'BF400', category = 'Motorcycles', supported = true },
    { model = 'carbonrs', label = 'Carbon RS', category = 'Motorcycles', supported = true },
    { model = 'chimera', label = 'Chimera', category = 'Motorcycles', supported = true },
    { model = 'cliffhanger', label = 'Cliffhanger', category = 'Motorcycles', supported = true },
    { model = 'daemon', label = 'Daemon', category = 'Motorcycles', supported = true },
    { model = 'daemon2', label = 'Daemon Custom', category = 'Motorcycles', supported = true },
    { model = 'deathbike', label = 'Apocalypse Deathbike', category = 'Motorcycles', supported = true },
    { model = 'deathbike2', label = 'Future Shock Deathbike', category = 'Motorcycles', supported = true },
    { model = 'deathbike3', label = 'Nightmare Deathbike', category = 'Motorcycles', supported = true },
    { model = 'defiler', label = 'Defiler', category = 'Motorcycles', supported = true },
    { model = 'diablous', label = 'Diabolus', category = 'Motorcycles', supported = true },
    { model = 'diablous2', label = 'Diabolus Custom', category = 'Motorcycles', supported = true },
    { model = 'double', label = 'Double-T', category = 'Motorcycles', supported = true },
    { model = 'enduro', label = 'Enduro', category = 'Motorcycles', supported = true },
    { model = 'esskey', label = 'Esskey', category = 'Motorcycles', supported = true },
    { model = 'faggio', label = 'Faggio Sport', category = 'Motorcycles', supported = true },
    { model = 'faggio2', label = 'Faggio', category = 'Motorcycles', supported = true },
    { model = 'faggio3', label = 'Faggio Mod', category = 'Motorcycles', supported = true },
    { model = 'fcr', label = 'FCR 1000', category = 'Motorcycles', supported = true },
    { model = 'fcr2', label = 'FCR 1000 Custom', category = 'Motorcycles', supported = true },
    { model = 'gargoyle', label = 'Gargoyle', category = 'Motorcycles', supported = true },
    { model = 'hakuchou', label = 'Hakuchou', category = 'Motorcycles', supported = true },
    { model = 'hakuchou2', label = 'Hakuchou Drag', category = 'Motorcycles', supported = true },
    { model = 'hexer', label = 'Hexer', category = 'Motorcycles', supported = true },
    { model = 'innovation', label = 'Innovation', category = 'Motorcycles', supported = true },
    { model = 'lectro', label = 'Lectro', category = 'Motorcycles', supported = true },
    { model = 'manchez', label = 'Manchez', category = 'Motorcycles', supported = true },
    { model = 'manchez2', label = 'Manchez Scout', category = 'Motorcycles', supported = true },
    { model = 'manchez3', label = 'Manchez Scout C', category = 'Motorcycles', supported = true },
    { model = 'nemesis', label = 'Nemesis', category = 'Motorcycles', supported = true },
    { model = 'nightblade', label = 'Nightblade', category = 'Motorcycles', supported = true },
    { model = 'oppressor', label = 'Oppressor', category = 'Motorcycles', supported = true },
    { model = 'oppressor2', label = 'Oppressor Mk II', category = 'Motorcycles', supported = true },
    { model = 'pcj', label = 'PCJ 600', category = 'Motorcycles', supported = true },
    { model = 'powersurge', label = 'Powersurge', category = 'Motorcycles', supported = true },
    { model = 'ratbike', label = 'Rat Bike', category = 'Motorcycles', supported = true },
    { model = 'reever', label = 'Reever', category = 'Motorcycles', supported = true },
    { model = 'rrocket', label = 'Rampant Rocket', category = 'Motorcycles', supported = true },
    { model = 'ruffian', label = 'Ruffian', category = 'Motorcycles', supported = true },
    { model = 'sanchez', label = 'Sanchez (livery)', category = 'Motorcycles', supported = true },
    { model = 'sanchez2', label = 'Sanchez', category = 'Motorcycles', supported = true },
    { model = 'sanctus', label = 'Sanctus', category = 'Motorcycles', supported = true },
    { model = 'shinobi', label = 'Shinobi', category = 'Motorcycles', supported = true },
    { model = 'shotaro', label = 'Shotaro', category = 'Motorcycles', supported = true },
    { model = 'sovereign', label = 'Sovereign', category = 'Motorcycles', supported = true },
    { model = 'stryder', label = 'Stryder', category = 'Motorcycles', supported = true },
    { model = 'thrust', label = 'Thrust', category = 'Motorcycles', supported = true },
    { model = 'vader', label = 'Vader', category = 'Motorcycles', supported = true },
    { model = 'vindicator', label = 'Vindicator', category = 'Motorcycles', supported = true },
    { model = 'vortex', label = 'Vortex', category = 'Motorcycles', supported = true },
    { model = 'wolfsbane', label = 'Wolfsbane', category = 'Motorcycles', supported = true },
    { model = 'zombiea', label = 'Zombie Bobber', category = 'Motorcycles', supported = true },
    { model = 'zombieb', label = 'Zombie Chopper', category = 'Motorcycles', supported = true },
    { model = 'bfinjection', label = 'Injection', category = 'Off-road', supported = true },
    { model = 'bifta', label = 'Bifta', category = 'Off-road', supported = true },
    { model = 'blazer', label = 'Blazer', category = 'Off-road', supported = true },
    { model = 'blazer2', label = 'Blazer Lifeguard', category = 'Off-road', supported = true },
    { model = 'blazer3', label = 'Hot Rod Blazer', category = 'Off-road', supported = true },
    { model = 'blazer4', label = 'Street Blazer', category = 'Off-road', supported = true },
    { model = 'blazer5', label = 'Blazer Aqua', category = 'Off-road', supported = true },
    { model = 'bodhi2', label = 'Bodhi', category = 'Off-road', supported = true },
    { model = 'boor', label = 'Boor', category = 'Off-road', supported = true },
    { model = 'brawler', label = 'Brawler', category = 'Off-road', supported = true },
    { model = 'bruiser', label = 'Apocalypse Bruiser', category = 'Off-road', supported = true },
    { model = 'bruiser2', label = 'Future Shock Bruiser', category = 'Off-road', supported = true },
    { model = 'bruiser3', label = 'Nightmare Bruiser', category = 'Off-road', supported = true },
    { model = 'brutus', label = 'Apocalypse Brutus', category = 'Off-road', supported = true },
    { model = 'brutus2', label = 'Future Shock Brutus', category = 'Off-road', supported = true },
    { model = 'brutus3', label = 'Nightmare Brutus', category = 'Off-road', supported = true },
    { model = 'caracara', label = 'Caracara', category = 'Off-road', supported = true },
    { model = 'caracara2', label = 'Caracara 4x4', category = 'Off-road', supported = true },
    { model = 'dloader', label = 'Duneloader', category = 'Off-road', supported = true },
    { model = 'draugur', label = 'Draugur', category = 'Off-road', supported = true },
    { model = 'driftl352', label = 'Drift Walkton L35', category = 'Off-road', supported = true },
    { model = 'dubsta3', label = 'Dubsta 6x6', category = 'Off-road', supported = true },
    { model = 'dune', label = 'Dune Buggy', category = 'Off-road', supported = true },
    { model = 'dune2', label = 'Space Docker', category = 'Off-road', supported = true },
    { model = 'dune3', label = 'Dune FAV', category = 'Off-road', supported = true },
    { model = 'dune4', label = 'Ramp Buggy', category = 'Off-road', supported = true },
    { model = 'dune5', label = 'Ramp Buggy', category = 'Off-road', supported = true },
    { model = 'freecrawler', label = 'Freecrawler', category = 'Off-road', supported = true },
    { model = 'hellion', label = 'Hellion', category = 'Off-road', supported = true },
    { model = 'insurgent', label = 'Insurgent Pick-Up', category = 'Off-road', supported = true },
    { model = 'insurgent2', label = 'Insurgent', category = 'Off-road', supported = true },
    { model = 'insurgent3', label = 'Insurgent Pick-Up Custom', category = 'Off-road', supported = true },
    { model = 'kalahari', label = 'Kalahari', category = 'Off-road', supported = true },
    { model = 'kamacho', label = 'Kamacho', category = 'Off-road', supported = true },
    { model = 'l35', label = 'Walton L35', category = 'Off-road', supported = true },
    { model = 'l352', label = 'Walton L35 Stock', category = 'Off-road', supported = true },
    { model = 'marshall', label = 'Marshall', category = 'Off-road', supported = true },
    { model = 'menacer', label = 'Menacer', category = 'Off-road', supported = true },
    { model = 'mesa3', label = 'Mesa', category = 'Off-road', supported = true },
    { model = 'monster', label = 'Monster', category = 'Off-road', supported = true },
    { model = 'monster3', label = 'Apocalypse Sasquatch', category = 'Off-road', supported = true },
    { model = 'monster4', label = 'Future Shock Sasquatch', category = 'Off-road', supported = true },
    { model = 'monster5', label = 'Nightmare Sasquatch', category = 'Off-road', supported = true },
    { model = 'monstrociti', label = 'MonstroCiti', category = 'Off-road', supported = true },
    { model = 'nightshark', label = 'Nightshark', category = 'Off-road', supported = true },
    { model = 'outlaw', label = 'Outlaw', category = 'Off-road', supported = true },
    { model = 'patriot3', label = 'Patriot Mil-Spec', category = 'Off-road', supported = true },
    { model = 'rancherxl', label = 'Rancher XL', category = 'Off-road', supported = true },
    { model = 'rancherxl2', label = 'Rancher XL', category = 'Off-road', supported = true },
    { model = 'ratel', label = 'Ratel', category = 'Off-road', supported = true },
    { model = 'rcbandito', label = 'RC Bandito', category = 'Off-road', supported = true },
    { model = 'rebel', label = 'Rusty Rebel', category = 'Off-road', supported = true },
    { model = 'rebel2', label = 'Rebel', category = 'Off-road', supported = true },
    { model = 'riata', label = 'Riata', category = 'Off-road', supported = true },
    { model = 'sandking', label = 'Sandking XL', category = 'Off-road', supported = true },
    { model = 'sandking2', label = 'Sandking SWB', category = 'Off-road', supported = true },
    { model = 'technical', label = 'Technical', category = 'Off-road', supported = true },
    { model = 'technical2', label = 'Technical Aqua', category = 'Off-road', supported = true },
    { model = 'technical3', label = 'Technical Custom', category = 'Off-road', supported = true },
    { model = 'terminus', label = 'Terminus', category = 'Off-road', supported = true },
    { model = 'trophytruck', label = 'Trophy Truck', category = 'Off-road', supported = true },
    { model = 'trophytruck2', label = 'Desert Raid', category = 'Off-road', supported = true },
    { model = 'vagrant', label = 'Vagrant', category = 'Off-road', supported = true },
    { model = 'verus', label = 'Verus', category = 'Off-road', supported = true },
    { model = 'winky', label = 'Winky', category = 'Off-road', supported = true },
    { model = 'yosemite3', label = 'Yosemite Rancher', category = 'Off-road', supported = true },
    { model = 'zhaba', label = 'Zhaba', category = 'Off-road', supported = true },
    { model = 'bulldozer', label = 'Dozer', category = 'Industrial', supported = true },
    { model = 'cutter', label = 'Cutter', category = 'Industrial', supported = true },
    { model = 'dump', label = 'Dump', category = 'Industrial', supported = true },
    { model = 'flatbed', label = 'Flatbed', category = 'Industrial', supported = true },
    { model = 'flatbed2', label = 'Custom Flatbed', category = 'Industrial', supported = true },
    { model = 'guardian', label = 'Guardian', category = 'Industrial', supported = true },
    { model = 'handler', label = 'Dock Handler', category = 'Industrial', supported = true },
    { model = 'mixer', label = 'Mixer', category = 'Industrial', supported = true },
    { model = 'mixer2', label = 'Mixer', category = 'Industrial', supported = true },
    { model = 'rubble', label = 'Rubble', category = 'Industrial', supported = true },
    { model = 'tiptruck', label = 'Tipper', category = 'Industrial', supported = true },
    { model = 'tiptruck2', label = 'Tipper', category = 'Industrial', supported = true },
    { model = 'airtug', label = 'Airtug', category = 'Utility', supported = true },
    { model = 'boattrailer2', label = 'Boat Trailer', category = 'Utility', supported = true },
    { model = 'boattrailer3', label = 'Boat Trailer', category = 'Utility', supported = true },
    { model = 'caddy', label = 'Caddy', category = 'Utility', supported = true },
    { model = 'caddy2', label = 'Caddy', category = 'Utility', supported = true },
    { model = 'caddy3', label = 'Caddy', category = 'Utility', supported = true },
    { model = 'driftkeitora', label = 'Keitora', category = 'Utility', supported = true },
    { model = 'docktug', label = 'Docktug', category = 'Utility', supported = true },
    { model = 'forklift', label = 'Forklift', category = 'Utility', supported = true },
    { model = 'keitora', label = 'Keitora', category = 'Utility', supported = true },
    { model = 'mower', label = 'Lawn Mower', category = 'Utility', supported = true },
    { model = 'ripley', label = 'Ripley', category = 'Utility', supported = true },
    { model = 'sadler', label = 'Sadler', category = 'Utility', supported = true },
    { model = 'sadler2', label = 'Sadler', category = 'Utility', supported = true },
    { model = 'scrap', label = 'Scrap Truck', category = 'Utility', supported = true },
    { model = 'slamtruck', label = 'Slamtruck', category = 'Utility', supported = true },
    { model = 'towtruck', label = 'Tow Truck', category = 'Utility', supported = true },
    { model = 'towtruck2', label = 'Tow Truck', category = 'Utility', supported = true },
    { model = 'towtruck3', label = 'Tow Truck', category = 'Utility', supported = true },
    { model = 'towtruck4', label = 'Tow Truck', category = 'Utility', supported = true },
    { model = 'tractor', label = 'Tractor', category = 'Utility', supported = true },
    { model = 'tractor2', label = 'Fieldmaster', category = 'Utility', supported = true },
    { model = 'tractor3', label = 'Fieldmaster', category = 'Utility', supported = true },
    { model = 'tvtrailer2', label = 'Trailer', category = 'Utility', supported = true },
    { model = 'utillitruck', label = 'Utility Truck', category = 'Utility', supported = true },
    { model = 'utillitruck2', label = 'Utility Truck', category = 'Utility', supported = true },
    { model = 'utillitruck3', label = 'Utility Truck', category = 'Utility', supported = true },
    { model = 'bison', label = 'Bison', category = 'Vans', supported = true },
    { model = 'bison2', label = 'Bison', category = 'Vans', supported = true },
    { model = 'bison3', label = 'Bison', category = 'Vans', supported = true },
    { model = 'bobcatxl', label = 'Bobcat XL', category = 'Vans', supported = true },
    { model = 'boxville', label = 'Boxville', category = 'Vans', supported = true },
    { model = 'boxville2', label = 'Boxville', category = 'Vans', supported = true },
    { model = 'boxville3', label = 'Boxville', category = 'Vans', supported = true },
    { model = 'boxville4', label = 'Boxville', category = 'Vans', supported = true },
    { model = 'boxville5', label = 'Armored Boxville', category = 'Vans', supported = true },
    { model = 'boxville6', label = 'Boxville (LSDS)', category = 'Vans', supported = true },
    { model = 'burrito', label = 'Burrito', category = 'Vans', supported = true },
    { model = 'burrito2', label = 'Bugstars Burrito', category = 'Vans', supported = true },
    { model = 'burrito3', label = 'Burrito', category = 'Vans', supported = true },
    { model = 'burrito4', label = 'Burrito', category = 'Vans', supported = true },
    { model = 'burrito5', label = 'Burrito', category = 'Vans', supported = true },
    { model = 'camper', label = 'Camper', category = 'Vans', supported = true },
    { model = 'gburrito', label = 'Gang Burrito', category = 'Vans', supported = true },
    { model = 'gburrito2', label = 'Gang Burrito', category = 'Vans', supported = true },
    { model = 'journey', label = 'Journey', category = 'Vans', supported = true },
    { model = 'journey2', label = 'Journey II', category = 'Vans', supported = true },
    { model = 'minivan', label = 'Minivan', category = 'Vans', supported = true },
    { model = 'minivan2', label = 'Minivan Custom', category = 'Vans', supported = true },
    { model = 'paradise', label = 'Paradise', category = 'Vans', supported = true },
    { model = 'pony', label = 'Pony', category = 'Vans', supported = true },
    { model = 'pony2', label = 'Pony', category = 'Vans', supported = true },
    { model = 'rumpo', label = 'Rumpo', category = 'Vans', supported = true },
    { model = 'rumpo2', label = 'Rumpo', category = 'Vans', supported = true },
    { model = 'rumpo3', label = 'Rumpo Custom', category = 'Vans', supported = true },
    { model = 'speedo', label = 'Speedo', category = 'Vans', supported = true },
    { model = 'speedo2', label = 'Clown Van', category = 'Vans', supported = true },
    { model = 'speedo4', label = 'Speedo Custom', category = 'Vans', supported = true },
    { model = 'speedo5', label = 'Speedo Custom', category = 'Vans', supported = true },
    { model = 'surfer', label = 'Surfer', category = 'Vans', supported = true },
    { model = 'surfer2', label = 'Surfer', category = 'Vans', supported = true },
    { model = 'surfer3', label = 'Surfer Custom', category = 'Vans', supported = true },
    { model = 'taco', label = 'Taco Van', category = 'Vans', supported = true },
    { model = 'youga', label = 'Youga', category = 'Vans', supported = true },
    { model = 'youga2', label = 'Youga Classic', category = 'Vans', supported = true },
    { model = 'youga3', label = 'Youga Classic 4x4', category = 'Vans', supported = true },
    { model = 'youga4', label = 'Youga Custom', category = 'Vans', supported = true },
    { model = 'bmx', label = 'BMX', category = 'Cycles', supported = true },
    { model = 'cruiser', label = 'Cruiser', category = 'Cycles', supported = true },
    { model = 'fixter', label = 'Fixter', category = 'Cycles', supported = true },
    { model = 'inductor', label = 'Inductor', category = 'Cycles', supported = true },
    { model = 'inductor2', label = 'Junk Energy Inductor', category = 'Cycles', supported = true },
    { model = 'scorcher', label = 'Scorcher', category = 'Cycles', supported = true },
    { model = 'tribike', label = 'Whippet Race Bike', category = 'Cycles', supported = true },
    { model = 'tribike2', label = 'Endurex Race Bike', category = 'Cycles', supported = true },
    { model = 'tribike3', label = 'Tri-Cycles Race Bike', category = 'Cycles', supported = true },
    { model = 'avisa', label = 'Avisa', category = 'Boats', supported = true },
    { model = 'dinghy', label = 'Dinghy', category = 'Boats', supported = true },
    { model = 'dinghy2', label = 'Dinghy', category = 'Boats', supported = true },
    { model = 'dinghy3', label = 'Dinghy', category = 'Boats', supported = true },
    { model = 'dinghy4', label = 'Dinghy', category = 'Boats', supported = true },
    { model = 'dinghy5', label = 'Weaponized Dinghy', category = 'Boats', supported = true },
    { model = 'jetmax', label = 'Jetmax', category = 'Boats', supported = true },
    { model = 'kosatka', label = 'Kosatka', category = 'Boats', supported = true },
    { model = 'longfin', label = 'Longfin', category = 'Boats', supported = true },
    { model = 'marquis', label = 'Marquis', category = 'Boats', supported = true },
    { model = 'patrolboat', label = 'Kurtz 31 Patrol Boat', category = 'Boats', supported = true },
    { model = 'predator', label = 'Police Predator', category = 'Boats', supported = true },
    { model = 'seashark', label = 'Seashark', category = 'Boats', supported = true },
    { model = 'seashark2', label = 'Seashark', category = 'Boats', supported = true },
    { model = 'seashark3', label = 'Seashark', category = 'Boats', supported = true },
    { model = 'speeder', label = 'Speeder', category = 'Boats', supported = true },
    { model = 'speeder2', label = 'Speeder', category = 'Boats', supported = true },
    { model = 'squalo', label = 'Squalo', category = 'Boats', supported = true },
    { model = 'submersible', label = 'Submersible', category = 'Boats', supported = true },
    { model = 'submersible2', label = 'Kraken', category = 'Boats', supported = true },
    { model = 'suntrap', label = 'Suntrap', category = 'Boats', supported = true },
    { model = 'toro', label = 'Toro', category = 'Boats', supported = true },
    { model = 'toro2', label = 'Toro', category = 'Boats', supported = true },
    { model = 'tropic', label = 'Tropic', category = 'Boats', supported = true },
    { model = 'tropic2', label = 'Tropic', category = 'Boats', supported = true },
    { model = 'tug', label = 'Tug', category = 'Boats', supported = true },
    { model = 'akula', label = 'Akula', category = 'Helicopters', supported = true },
    { model = 'annihilator', label = 'Annihilator', category = 'Helicopters', supported = true },
    { model = 'annihilator2', label = 'Annihilator Stealth', category = 'Helicopters', supported = true },
    { model = 'buzzard', label = 'Buzzard Attack Chopper', category = 'Helicopters', supported = true },
    { model = 'buzzard2', label = 'Buzzard', category = 'Helicopters', supported = true },
    { model = 'cargobob', label = 'Cargobob', category = 'Helicopters', supported = true },
    { model = 'cargobob2', label = 'Cargobob', category = 'Helicopters', supported = true },
    { model = 'cargobob3', label = 'Cargobob', category = 'Helicopters', supported = true },
    { model = 'cargobob4', label = 'Cargobob', category = 'Helicopters', supported = true },
    { model = 'conada', label = 'Conada', category = 'Helicopters', supported = true },
    { model = 'conada2', label = 'Weaponized Conada', category = 'Helicopters', supported = true },
    { model = 'frogger', label = 'Frogger', category = 'Helicopters', supported = true },
    { model = 'frogger2', label = 'Frogger', category = 'Helicopters', supported = true },
    { model = 'havok', label = 'Havok', category = 'Helicopters', supported = true },
    { model = 'hunter', label = 'FH-1 Hunter', category = 'Helicopters', supported = true },
    { model = 'maverick', label = 'Maverick', category = 'Helicopters', supported = true },
    { model = 'maverick2', label = 'Higgins Helitours Maverick', category = 'Helicopters', supported = true },
    { model = 'polmav', label = 'Police Maverick', category = 'Helicopters', supported = true },
    { model = 'savage', label = 'Savage', category = 'Helicopters', supported = true },
    { model = 'seasparrow', label = 'Sea Sparrow', category = 'Helicopters', supported = true },
    { model = 'seasparrow2', label = 'Sparrow', category = 'Helicopters', supported = true },
    { model = 'seasparrow3', label = 'Sparrow', category = 'Helicopters', supported = true },
    { model = 'skylift', label = 'Skylift', category = 'Helicopters', supported = true },
    { model = 'supervolito', label = 'SuperVolito', category = 'Helicopters', supported = true },
    { model = 'supervolito2', label = 'SuperVolito Carbon', category = 'Helicopters', supported = true },
    { model = 'swift', label = 'Swift', category = 'Helicopters', supported = true },
    { model = 'swift2', label = 'Swift Deluxe', category = 'Helicopters', supported = true },
    { model = 'valkyrie', label = 'Valkyrie', category = 'Helicopters', supported = true },
    { model = 'valkyrie2', label = 'Valkyrie MOD.0', category = 'Helicopters', supported = true },
    { model = 'volatus', label = 'Volatus', category = 'Helicopters', supported = true },
    { model = 'alkonost', label = 'RO-86 Alkonost', category = 'Planes', supported = true },
    { model = 'alphaz1', label = 'Alpha-Z1', category = 'Planes', supported = true },
    { model = 'avenger', label = 'Avenger', category = 'Planes', supported = true },
    { model = 'avenger2', label = 'Avenger', category = 'Planes', supported = true },
    { model = 'avenger3', label = 'Avenger', category = 'Planes', supported = true },
    { model = 'avenger4', label = 'Avenger', category = 'Planes', supported = true },
    { model = 'besra', label = 'Besra', category = 'Planes', supported = true },
    { model = 'blimp', label = 'Atomic Blimp', category = 'Planes', supported = true },
    { model = 'blimp2', label = 'Xero Blimp', category = 'Planes', supported = true },
    { model = 'blimp3', label = 'Blimp', category = 'Planes', supported = true },
    { model = 'bombushka', label = 'RM-10 Bombushka', category = 'Planes', supported = true },
    { model = 'cargoplane', label = 'Cargo Plane', category = 'Planes', supported = true },
    { model = 'cargoplane2', label = 'Cargo Plane', category = 'Planes', supported = true },
    { model = 'cuban800', label = 'Cuban 800', category = 'Planes', supported = true },
    { model = 'dodo', label = 'Dodo', category = 'Planes', supported = true },
    { model = 'duster', label = 'Duster', category = 'Planes', supported = true },
    { model = 'howard', label = 'Howard NX-25', category = 'Planes', supported = true },
    { model = 'hydra', label = 'Hydra', category = 'Planes', supported = true },
    { model = 'jet', label = 'Jet', category = 'Planes', supported = true },
    { model = 'lazer', label = 'P-996 LAZER', category = 'Planes', supported = true },
    { model = 'luxor', label = 'Luxor', category = 'Planes', supported = true },
    { model = 'luxor2', label = 'Luxor Deluxe', category = 'Planes', supported = true },
    { model = 'mammatus', label = 'Mammatus', category = 'Planes', supported = true },
    { model = 'microlight', label = 'Ultralight', category = 'Planes', supported = true },
    { model = 'miljet', label = 'Miljet', category = 'Planes', supported = true },
    { model = 'mogul', label = 'Mogul', category = 'Planes', supported = true },
    { model = 'molotok', label = 'V-65 Molotok', category = 'Planes', supported = true },
    { model = 'nimbus', label = 'Nimbus', category = 'Planes', supported = true },
    { model = 'nokota', label = 'P-45 Nokota', category = 'Planes', supported = true },
    { model = 'pyro', label = 'Pyro', category = 'Planes', supported = true },
    { model = 'raiju', label = 'F-160 Raiju', category = 'Planes', supported = true },
    { model = 'rogue', label = 'Rogue', category = 'Planes', supported = true },
    { model = 'seabreeze', label = 'Seabreeze', category = 'Planes', supported = true },
    { model = 'shamal', label = 'Shamal', category = 'Planes', supported = true },
    { model = 'starling', label = 'LF-22 Starling', category = 'Planes', supported = true },
    { model = 'streamer216', label = 'Streamer216', category = 'Planes', supported = true },
    { model = 'strikeforce', label = 'B-11 Strikeforce', category = 'Planes', supported = true },
    { model = 'stunt', label = 'Mallard', category = 'Planes', supported = true },
    { model = 'titan', label = 'Titan', category = 'Planes', supported = true },
    { model = 'tula', label = 'Tula', category = 'Planes', supported = true },
    { model = 'velum', label = 'Velum', category = 'Planes', supported = true },
    { model = 'velum2', label = 'Velum 5-Seater', category = 'Planes', supported = true },
    { model = 'vestra', label = 'Vestra', category = 'Planes', supported = true },
    { model = 'volatol', label = 'Volatol', category = 'Planes', supported = true },
    { model = 'airbus', label = 'Airport Bus', category = 'Service', supported = true },
    { model = 'brickade', label = 'Brickade', category = 'Service', supported = true },
    { model = 'brickade2', label = 'Brickade 6x6', category = 'Service', supported = true },
    { model = 'bus', label = 'Bus', category = 'Service', supported = true },
    { model = 'coach', label = 'Dashound', category = 'Service', supported = true },
    { model = 'pbus2', label = 'Festival Bus', category = 'Service', supported = true },
    { model = 'rallytruck', label = 'Dune', category = 'Service', supported = true },
    { model = 'rentalbus', label = 'Rental Shuttle Bus', category = 'Service', supported = true },
    { model = 'taxi', label = 'Taxi', category = 'Service', supported = true },
    { model = 'tourbus', label = 'Tour Bus', category = 'Service', supported = true },
    { model = 'trash', label = 'Trashmaster', category = 'Service', supported = true },
    { model = 'trash2', label = 'Trashmaster', category = 'Service', supported = true },
    { model = 'vivanite2', label = 'Vivanite', category = 'Service', supported = true },
    { model = 'wastelander', label = 'Wastelander', category = 'Service', supported = true },
    { model = 'ambulance', label = 'Ambulance', category = 'Emergency', supported = true },
    { model = 'fbi', label = 'FIB', category = 'Emergency', supported = true },
    { model = 'fbi2', label = 'FIB', category = 'Emergency', supported = true },
    { model = 'firetruk', label = 'Fire Truck', category = 'Emergency', supported = true },
    { model = 'lguard', label = 'Lifeguard', category = 'Emergency', supported = true },
    { model = 'pbus', label = 'Police Prison Bus', category = 'Emergency', supported = true },
    { model = 'polbuffalo', label = 'Buffalo Cruiser', category = 'Emergency', supported = true },
    { model = 'polbuffalo6', label = 'Buffalo STX Pursuit', category = 'Emergency', supported = true },
    { model = 'polgauntlet', label = 'Gauntlet Interceptor', category = 'Emergency', supported = true },
    { model = 'police', label = 'Police Cruiser', category = 'Emergency', supported = true },
    { model = 'police2', label = 'Police Cruiser', category = 'Emergency', supported = true },
    { model = 'police3', label = 'Police Cruiser', category = 'Emergency', supported = true },
    { model = 'police4', label = 'Unmarked Cruiser', category = 'Emergency', supported = true },
    { model = 'police5', label = 'Stanier LE Cruiser', category = 'Emergency', supported = true },
    { model = 'policeb', label = 'Police Bike', category = 'Emergency', supported = true },
    { model = 'policeb2', label = 'Police Bike', category = 'Emergency', supported = true },
    { model = 'policeold1', label = 'Police Rancher', category = 'Emergency', supported = true },
    { model = 'policeold2', label = 'Police Roadcruiser', category = 'Emergency', supported = true },
    { model = 'policet', label = 'Police Transporter', category = 'Emergency', supported = true },
    { model = 'pranger', label = 'Park Ranger', category = 'Emergency', supported = true },
    { model = 'riot', label = 'Police Riot', category = 'Emergency', supported = true },
    { model = 'riot2', label = 'RCV', category = 'Emergency', supported = true },
    { model = 'sheriff', label = 'Sheriff Cruiser', category = 'Emergency', supported = true },
    { model = 'sheriff2', label = 'Sheriff SUV', category = 'Emergency', supported = true },
    { model = 'apc', label = 'APC', category = 'Military', supported = true },
    { model = 'barracks', label = 'Barracks', category = 'Military', supported = true },
    { model = 'barracks2', label = 'Barracks Semi', category = 'Military', supported = true },
    { model = 'barracks3', label = 'Barracks', category = 'Military', supported = true },
    { model = 'barrage', label = 'Barrage', category = 'Military', supported = true },
    { model = 'chernobog', label = 'Chernobog', category = 'Military', supported = true },
    { model = 'crusader', label = 'Crusader', category = 'Military', supported = true },
    { model = 'halftrack', label = 'Half-track', category = 'Military', supported = true },
    { model = 'khanjali', label = 'TM-02 Khanjali', category = 'Military', supported = true },
    { model = 'minitank', label = 'Invade and Persuade Tank', category = 'Military', supported = true },
    { model = 'rhino', label = 'Rhino Tank', category = 'Military', supported = true },
    { model = 'scarab', label = 'Apocalypse Scarab', category = 'Military', supported = true },
    { model = 'scarab2', label = 'Future Shock Scarab', category = 'Military', supported = true },
    { model = 'scarab3', label = 'Nightmare Scarab', category = 'Military', supported = true },
    { model = 'thruster', label = 'Thruster', category = 'Military', supported = true },
    { model = 'vetir', label = 'Vetir', category = 'Military', supported = true },
    { model = 'benson', label = 'Benson', category = 'Commercial', supported = true },
    { model = 'benson2', label = "Benson (Cluckin' Bell)", category = 'Commercial', supported = true },
    { model = 'biff', label = 'Biff', category = 'Commercial', supported = true },
    { model = 'cerberus', label = 'Apocalypse Cerberus', category = 'Commercial', supported = true },
    { model = 'cerberus2', label = 'Future Shock Cerberus', category = 'Commercial', supported = true },
    { model = 'cerberus3', label = 'Nightmare Cerberus', category = 'Commercial', supported = true },
    { model = 'hauler', label = 'Hauler', category = 'Commercial', supported = true },
    { model = 'hauler2', label = 'Hauler Custom', category = 'Commercial', supported = true },
    { model = 'mule', label = 'Mule', category = 'Commercial', supported = true },
    { model = 'mule2', label = 'Mule', category = 'Commercial', supported = true },
    { model = 'mule3', label = 'Mule', category = 'Commercial', supported = true },
    { model = 'mule4', label = 'Mule Custom', category = 'Commercial', supported = true },
    { model = 'mule5', label = 'Mule', category = 'Commercial', supported = true },
    { model = 'packer', label = 'Packer', category = 'Commercial', supported = true },
    { model = 'phantom', label = 'Phantom', category = 'Commercial', supported = true },
    { model = 'phantom2', label = 'Phantom Wedge', category = 'Commercial', supported = true },
    { model = 'phantom3', label = 'Phantom Custom', category = 'Commercial', supported = true },
    { model = 'phantom4', label = 'Phantom', category = 'Commercial', supported = true },
    { model = 'pounder', label = 'Pounder', category = 'Commercial', supported = true },
    { model = 'pounder2', label = 'Pounder Custom', category = 'Commercial', supported = true },
    { model = 'stockade', label = 'Stockade', category = 'Commercial', supported = true },
    { model = 'stockade3', label = 'Stockade', category = 'Commercial', supported = true },
    { model = 'stockade4', label = 'Bobcat Security Stockade', category = 'Commercial', supported = true },
    { model = 'terbyte', label = 'Terrorbyte', category = 'Commercial', supported = true },
    { model = 'freight', label = 'Freight Train', category = 'Trains', supported = false },
    { model = 'freight2', label = 'Freight Train', category = 'Trains', supported = false },
    { model = 'freightcar', label = 'Freight Train', category = 'Trains', supported = false },
    { model = 'freightcar2', label = 'Freight Train', category = 'Trains', supported = false },
    { model = 'freightcont1', label = 'Freight Train', category = 'Trains', supported = false },
    { model = 'freightcont2', label = 'Freight Train', category = 'Trains', supported = false },
    { model = 'freightgrain', label = 'Freight Train', category = 'Trains', supported = false },
    { model = 'metrotrain', label = 'Freight Train', category = 'Trains', supported = false },
    { model = 'tankercar', label = 'Freight Train', category = 'Trains', supported = false },
    { model = 'formula', label = 'PR4', category = 'Open Wheel', supported = true },
    { model = 'formula2', label = 'R88', category = 'Open Wheel', supported = true },
    { model = 'openwheel1', label = 'BR8', category = 'Open Wheel', supported = true },
    { model = 'openwheel2', label = 'DR1', category = 'Open Wheel', supported = true },
}
